sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: IYi4KfuhDyOKo50YS62NEIRZpXMGNKkIryxnj0xizlq60rTmGoVtWX7KBSsIqUsPg7MPMHNR/jhaKamxNrlyAbOLqJndW2OrHwn2NvM1Df7njiNJWevdlZNIznXxow5TrEIGth2DLzgSD1vKR6Yz/5tcMXW49AKYYLP8SBtqRN+iOMqSK6ae45qXx+YfcuyttsDGO1K73MqCpIuRoch0qAlN5GUulANOwEU0CuJWr+hKJemTwsfRrnDDSWwYucEE/TTegnuZy0KIwwBBUfDyr8rQiacR8JWwt4ZGYFbz3GHMoMX8tvpv/adXMc+Ij41Ive1GPM2K3BOf2dyMiZdBQS9qHiTvaFspbhd2vaGnDmJe17DSz4IWf4u11FMHnNbSq5vxbQkGXhsw4wPokk0PWG/yPVhHTUEtEJckpwDsHlbB1VHzHJfjXGq249Sf/J2FT3E48CWJiTO4dJQlGoa4jyNi+7rsDbKy0Ha5IRI3auybnzTO7vw+uAK1YHGvM5bF2iRx9EVvnAYmTPcwOhoxordevPdsfVhhyUGOcN7Amvv088hBx13j8NqQJDlu5pJRP/Z+oZ+GMZrzqAJ+G6vaHCOFq1AqFC+TqGEPqb0aGMuc16Hs7gfuppnu8GewCZ5RCJwWGxIA/Ky/qXGGdDcbHF25GsqAfeGdHIPureJEoDc=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Trinity-Site-1945-1995-A-National-Historic-Landmark-White-Sands-Missile-Range-New-Mexico_278
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy